apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-lister
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-lister-binding
  namespace: default
subjects:
  - kind: User
    name: varun_teja@crickbuz.com  # Replace with the actual email ID of QA
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-lister
  apiGroup: rbac.authorization.k8s.io
