apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-lister
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-lister-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: qa-serviceaccount  # The ServiceAccount that gets the role
    namespace: default      # The namespace where the ServiceAccount is located
roleRef:
  kind: Role
  name: pod-lister  # The Role to bind
  apiGroup: rbac.authorization.k8s.io
